contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    # Index da pagina
    path('search/', views.search, name='search' ),
    path('', views.index, name='index' ),
    # visitante (CRUD) 
    path('visitantes/<int:visitante_id>/detail/', 
         views.visitanteIndex, name='visitanteIndex' ),
    path('visitantes/create/', views.create_visitantes, 
         name='create_visitantes' ),
    path('visitantes/<int:visitante_id>/update/', 
         views.visitanteIndexUpdate, name='visitanteIndexUpdate' ),

    # Busca do Registro de Visitantes
    path('search/registro_visitantes/', views.registro_visitantes_index_busca, 
         name='registro_visitantes_index_busca' ),
    path('registro_visitantes/', views.registro_visitantes_index, 
         name='registro_visitantes_index' ),
    # REGISTRO VISITANTES CRUD
    path('registro_visitantes/<int:registro_id>/detail/', 
         views.registro_visitantes_index_contato, 
         name='registro_visitantes_index_contato' ),
    path('registro_visitantes/create_registro_visitantes/', 
         views.create_registro_de_visitantes, 
         name='create_registro_de_visitantes' ),
    path('registro_visitantes/<int:registro_id>/update/', 
         views.update_registro_de_visitantes, 
         name='update_registro_de_visitantes' ),

    # URL de Registro de entregas
    path('search/registro_entregas/', views.registro_entregas_index_busca, 
         name='registro_entregas_index_busca' ),
    path('registro_entregas/', views.registro_entregas_index, 
         name='registro_entregas_index' ),
    # CRUDde Registro de entregas
    path('registro_entregas_index_contato/<int:entregas_id>/detail/', 
         views.registro_entregas_index_contato, 
         name='registro_entregas_index_contato' ),
    path('registro_entregas/create_entregas/', views.entregas, 
         name='create_entregas' ),
    path('registro_entregas_index_contato/<int:entregas_id>/update/', 
         views.update_entregas, 
         name='update_entregas' ),

     #URL MORADORES
    path('search/busca_moradores/', views.moradores_index_busca, 
         name='moradores_index_busca' ),
    path('moradores_index_id/<int:moradores_id>', views.moradores_index_id, 
         name='moradores_index_id' ),
    path('moradores/', views.moradores_index, 
         name='moradores_index' ),

     # URL dos carros condominio  carros_index_id
    path('carros_index_busca/', views.carros_index_busca, 
         name='carros_index_busca' ),
    path('contanto_veiculo_id/<int:carro_id>', views.carros_index_id, 
         name='carros_index_id' ),
    path('carros/', views.carros_index, 
         name='carros_index' ),

    # URL Ocorrencia
    path('ocorrencias_busca/', views.ocorrencias_index_busca, 
         name='ocorrencias_index_busca' ),
    path('ocorrencias_index/', views.ocorrencias_index, 
         name='ocorrencias_index' ),
    # CRUD Ocorrencia
    path('ocorrencias_id/create_ocorrencia/', views.ocorrenciaIndex , 
         name='ocorrenciaIndex' ),
    path('ocorrencias_id/<int:id_ocorrencia>/detail/', 
         views.ocorrencias_index_id, 
         name='ocorrencias_index_id' ),
    path('ocorrencias_id/<int:id_ocorrencia>/update/', 
         views.ocorrenciaUpdate, 
         name='ocorrenciaUpdate' ),
     # URL Eventos
    path('index_eventos/', views.eventos, name='eventos' ),
    path('eventos_busca/', views.eventos_busca, name='eventos_busca' ),
     # CRUD Eventos
    path('eventos_busca/<int:eventos_id>/detail/', views.eventos_id, 
         name='eventos_id' ),
    path('eventos_busca/create_eventos/', views.create_eventos, 
         name='create_eventos' ),
    path('eventos_busca/<int:eventos_id>/update_eventos/', 
         views.update_eventos, name='update_eventos' ),
    path('eventos_busca/<int:eventos_id>/delete/', views.delete, 
         name='delete' ),



     # User Register
    path('user/create_user/', views.register, name='register' ),
    path('user/login/', views.login_views, name='login_views' ),
    path('user/logaut/', views.logaut_views, name='logaut_views' ),
    path('user/update/', views.user_update, name='user_update' ),
















]


project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('porteiros/', include('contact.urls')),
    path('moradores/', include('moradores.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from contact.forms import VisitantesForm, Registro_visitantesForm, Registros_de_EntregaForm, OcorrenciaForm, EventosForm
from django.urls import reverse
from contact.models import Visitante,Registro_de_Visitante, Registros_de_Entrega, Ocorrencia, Eventos
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from contact.views.user_forms import *

@porteiro_required
def create_visitantes(request):
    form_action = reverse('contact:create_visitantes')

    if request.method == 'POST':
        form_visitantes = VisitantesForm(request.POST)

        context = {
            'form': form_visitantes,
            'form_action': form_action,
        }

        if form_visitantes.is_valid():
            form_visitantes.save()
            messages.success(request, 'Visitante Registrado com Sucesso!')
            return redirect('contact:index')

        return render(
            request,
            'contact/visitantes/create.html',
            context,
        )

    context = {
        'form': VisitantesForm(),
        'form_action': form_action,
    }
    return render(
        request,
        'contact/visitantes/create.html',
        context,
    )

@porteiro_required
def create_eventos(request):
    form_action = reverse('contact:create_eventos')
    if request.method == 'POST':
        form_eventos = EventosForm(request.POST)

        context = {
            'form': form_action,
            'form_eventos': form_eventos
        }

        if form_eventos.is_valid():
            form_eventos.save()
            messages.success(request, 'Agendado com sucesso!')
            return redirect('contact:eventos')
        return render(
            request,
            'contact/eventos/create_eventos.html',
            context,
        )
    context = {
            'form': EventosForm(),
            'form_eventos': form_action,
    }
    return render(
        request,
        'contact/eventos/create_eventos.html',
        context,
    )

@porteiro_required
def visitanteIndexUpdate(request, visitante_id):
    visitante = get_object_or_404(Visitante, pk=visitante_id)

    form_action = reverse('contact:visitanteIndexUpdate', args=(visitante_id,))

    if request.method == 'POST':
        form_visitantes = VisitantesForm(request.POST, instance=visitante)

        context = {
            'form': form_visitantes,
            'form_action': form_action,
        }

        if form_visitantes.is_valid():
            id_visitante = form_visitantes.save()
            messages.success(request, 'Visitante Atualizado com sucesso!')
            return redirect('contact:visitanteIndex', visitante_id=id_visitante.pk)

        return render(
            request,
            'contact/visitantes/create.html',
            context,
        )

    context = {
        'form': VisitantesForm(instance=visitante),
        'form_action': form_action,
    }
    return render(
        request,
        'contact/visitantes/create.html',
        context,
    )

# Formulario de registro de visitantes
@porteiro_required
def create_registro_de_visitantes(request):
    form_action_registro_visitantes = reverse('contact:create_registro_de_visitantes')

    if request.method == 'POST':
        form_registro_visitantes = Registro_visitantesForm(request.POST, request.FILES)

        context = {
            'form': form_registro_visitantes,
            'form_action_registro_visitantes': form_action_registro_visitantes,
        }

        if form_registro_visitantes.is_valid():
            form_registro_visitantes.save()
            messages.success(request, 'Registro Cadastrado com sucesso!')
            messages.info(request, 'Agora cadastre no Visitante e coloque o ID do registro que você acabou de Registra')
            return redirect('contact:registro_visitantes_index')
            # return redirect('contact:visitanteIndexUpdate', visitante_id=visitante.pk)

        return render(
            request,
            'contact/registro_visitantes/create_registro_visitantes.html',
            context,
        )

    context = {
        'form': Registro_visitantesForm(),
        'form_action_registro_visitantes': form_action_registro_visitantes,
    }
    return render(
        request,
        'contact/registro_visitantes/create_registro_visitantes.html',
        context,
    )

# Formulario de update do registro de visitantes
@porteiro_required
def update_registro_de_visitantes(request, registro_id):
    registro = get_object_or_404(Registro_de_Visitante, pk=registro_id)

    form_action_registro_visitantes = reverse('contact:update_registro_de_visitantes', args=(registro_id,))

    if request.method == 'POST':
        form_registro_visitantes = Registro_visitantesForm(request.POST, request.FILES, instance=registro )
        context = {
            'form': form_registro_visitantes,
            'form_action_registro_visitantes': form_action_registro_visitantes,
        }
        if form_registro_visitantes.is_valid():
            id_resitro_visitante = form_registro_visitantes.save()
            messages.success(request, 'Atualizado com sucesso!')
            return redirect('contact:registro_visitantes_index_contato',registro_id = id_resitro_visitante.pk)
        return render(
            request,
            'contact/registro_visitantes/create_registro_visitantes.html',
            context,
        )
    context = {
        'form': Registro_visitantesForm(instance=registro),
        'form_action_registro_visitantes': form_action_registro_visitantes,
    }
    return render(
        request,
        'contact/registro_visitantes/create_registro_visitantes.html',
        context,
    )

@porteiro_required
def entregas(request):
    form_action_registro_entregas = reverse('contact:create_entregas')
    if request.method == 'POST':
        form_registro_entregas = Registros_de_EntregaForm(request.POST, request.FILES)
        context = {
            'form': form_action_registro_entregas,
            'form_registro_entregas': form_registro_entregas,
        }
        if form_registro_entregas.is_valid():
            form_registro_entregas.save()
            messages.success(request, 'Criado o Cadastrado com sucesso!')
            return redirect('contact:registro_entregas_index')
        return render(
                request,
                'contact/entregas/create_entregas.html',
                context,
            )
    context = {
        'form': Registros_de_EntregaForm(),
        'form_action_registro_entregas': form_action_registro_entregas,
    }
    return render(
        request,
        'contact/entregas/create_entregas.html',
        context,
    )

@porteiro_required
def update_entregas(request, entregas_id):
    entrega_update = get_object_or_404(Registros_de_Entrega, pk=entregas_id)

    form_action_registro_entregas = reverse('contact:update_entregas', args=(entregas_id,))

    if request.method == 'POST':
        form_registro_entregas = Registros_de_EntregaForm(request.POST, request.FILES, instance=entrega_update)

        context = {
            'form': form_action_registro_entregas,
            'form_registro_entregas': form_registro_entregas,
        }
        if form_registro_entregas.is_valid():
            id_entrega = form_registro_entregas.save()
            messages.success(request, 'Atualizado com sucesso!')
            return redirect('contact:registro_entregas_index_contato', entregas_id=id_entrega.pk )
        
        return render(
                request,
                'contact/entregas/create_entregas.html',
                context,
            )
    
    context = {
        'form': Registros_de_EntregaForm(instance=entrega_update),
        'form_action_registro_entregas': form_action_registro_entregas,
    }

    return render(
        request,
        'contact/entregas/create_entregas.html',
        context,
    )

@porteiro_required
def ocorrenciaIndex(request):
    form_action_ocorrecia = reverse('contact:ocorrenciaIndex')
    if request.method == 'POST':
        form_ocorrencia = OcorrenciaForm(request.POST)
        contex = {
            'form': form_action_ocorrecia,
            'form_ocorrencia' : form_ocorrencia,
        }
        if form_ocorrencia.is_valid():
            ocorrencia= form_ocorrencia.save(commit=False)
            ocorrencia.owner = request.user
            ocorrencia.save()
            messages.success(request, 'Criado com sucesso!')
            return redirect('contact:ocorrencias_index')
        return render(
            request,
            'contact/ocorrencias/create_livro.html',
            contex
        )
    context = {
        'form': OcorrenciaForm(),
        'form_action_ocorrecia': form_action_ocorrecia,
    }
    return render(
        request,
        'contact/ocorrencias/create_livro.html',
        context
    )

@porteiro_required
def ocorrenciaUpdate(request, id_ocorrencia):
    ocorrencia_update = get_object_or_404(Ocorrencia, pk=id_ocorrencia, owner=request.user)
    form_action_ocorrecia = reverse('contact:ocorrenciaUpdate', args=(id_ocorrencia,))
    if request.method == 'POST':
        form_ocorrencia = OcorrenciaForm(request.POST, instance = ocorrencia_update)
        contex = {
            'form': form_action_ocorrecia,
            'form_ocorrencia' : form_ocorrencia,
        }
        if form_ocorrencia.is_valid():
            ocorrencia = form_ocorrencia.save()
            messages.success(request, 'Atualizado com sucesso!')
            return redirect('contact:ocorrencias_index_id', id_ocorrencia=ocorrencia.pk)
        return render(
            request,

contact/templates/contact/veiculos/id_veiculos.html
{% extends "global/base.html" %}

{% block content %}

    <div class="single-contact">
        <h1 class="single-contact-name">

            {{ carro.nome_proprietario }}
        </h1>
        <p><b>Nome Proprietario:</b> {{ carro.nome_proprietario }}</p>
        <p><b>Placa:</b> {{ carro.placa }} </p>
        <p><b>Cor:</b> {{ carro.cor }}</p>
        <p><b>Modelo:</b> {{ carro.modelo }}</p>
        <p><b>Apartamento:</b> {{ carro.apartamento }}</p>
        <p><b>Obs:</b> {{ carro.obs }}</p>

        {% if carro.foto %}
            <p>
                <img src=" {{ carro.foto.url }} " alt=" {{ carro.nome_proprietario  }} ">
            </p>
        {% endif %}
        
        <div class="contact-links">
             <a class="btn btn-volta" 
                href="{% url 'contact:carros_index' %}">
                Volta
             </a>
        </div>
    </div>

{% endblock content %}

contact/templates/contact/veiculos/veiculos.html
{% extends "global/base.html" %}
{% block content %}  
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption" >
                Veiculos Ed. Palladium

                <div class="search">
                    <form action="{% url "contact:carros_index_busca" %}" 
                    method="GET">
                        <input 
                        type="text" 
                        class="search-input"
                        placeholder="Busca"
                        id="search"
                        name="q"
                        value="{{ request.GET.q.strip }}"
                        >
                    </form>
                </div>
                
                <a href="" class="header-link">
                    <h2>Veículos Ed. Palladium</h2>
                </a>
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">Placa</th>
                    <th class="table-header">Proprietario</th>
                    <th class="table-header">Cor</th>
                    <th class="table-header">Apartamento</th>
                </tr>
            </thead>
            
            <tbody>
                {% for carro in carros %}
                  <tr class="table-row">
                    <td class="table-cel">
                        {{ carro.placa}}
                    </td>
                    <td class="table-cel">
                        <a href="{% url "contact:carros_index_id" carro.id %}" 
                        class="table-link"
                        >
                        {{ carro.nome_proprietario }}
                        </a>
                    </td>
                    <td class="table-cel">
                        
                        {{ carro.cor }}
                    </td>
                    <td class="table-cel">
                        {{ carro.apartamento }}
                    </td>
                    
                  </tr>
                {% endfor %}        
            </tbody>
        
        </table>
    </div>

    {% if carros %}
        <div class="pagination">
            <span class="step-links">
                {% if carros.has_previous %}
                    <a href="?page=1&q={{ request.GET.q.strip }}">&laquo; primeira Pagina</a>
                    <a href="?page={{ carros.previous_page_number }}&q={{ request.GET.q.strip }}">Voltar</a>
                {% endif %}

                <span class="current">
                    Pagina {{ carros.number }} de {{ carros.paginator.num_pages }}.
                </span>

                {% if carros.has_next %}
                    <a href="?page={{ carros.next_page_number }}&q={{ request.GET.q.strip }}">Proxima Pagina</a>
                    <a href="?page={{ carros.paginator.num_pages }}&q={{ request.GET.q.strip }}">Final da Pagina &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

{% endblock content %}