contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    # Index da pagina
    path('search/', views.search, name='search' ),
    path('', views.index, name='index' ),
    # visitante (CRUD) 
    path('visitantes/<int:visitante_id>/detail/', 
         views.visitanteIndex, name='visitanteIndex' ),
    path('visitantes/create/', views.create_visitantes, 
         name='create_visitantes' ),
    path('visitantes/<int:visitante_id>/update/', 
         views.visitanteIndexUpdate, name='visitanteIndexUpdate' ),

    # Busca do Registro de Visitantes
    path('search/registro_visitantes/', views.registro_visitantes_index_busca, 
         name='registro_visitantes_index_busca' ),
    path('registro_visitantes/', views.registro_visitantes_index, 
         name='registro_visitantes_index' ),
    # REGISTRO VISITANTES CRUD
    path('registro_visitantes/<int:registro_id>/detail/', 
         views.registro_visitantes_index_contato, 
         name='registro_visitantes_index_contato' ),
    path('registro_visitantes/create_registro_visitantes/', 
         views.create_registro_de_visitantes, 
         name='create_registro_de_visitantes' ),
    path('registro_visitantes/<int:registro_id>/update/', 
         views.update_registro_de_visitantes, 
         name='update_registro_de_visitantes' ),

    # URL de Registro de entregas
    path('search/registro_entregas/', views.registro_entregas_index_busca, 
         name='registro_entregas_index_busca' ),
    path('registro_entregas/', views.registro_entregas_index, 
         name='registro_entregas_index' ),
    # CRUDde Registro de entregas
    path('registro_entregas_index_contato/<int:entregas_id>/detail/', 
         views.registro_entregas_index_contato, 
         name='registro_entregas_index_contato' ),
    path('registro_entregas/create_entregas/', views.entregas, 
         name='create_entregas' ),
    path('registro_entregas_index_contato/<int:entregas_id>/update/', 
         views.update_entregas, 
         name='update_entregas' ),

     #URL MORADORES
    path('search/busca_moradores/', views.moradores_index_busca, 
         name='moradores_index_busca' ),
    path('moradores_index_id/<int:moradores_id>', views.moradores_index_id, 
         name='moradores_index_id' ),
    path('moradores/', views.moradores_index, 
         name='moradores_index' ),

     # URL dos carros condominio  carros_index_id
    path('carros_index_busca/', views.carros_index_busca, 
         name='carros_index_busca' ),
    path('contanto_veiculo_id/<int:carro_id>', views.carros_index_id, 
         name='carros_index_id' ),
    path('carros/', views.carros_index, 
         name='carros_index' ),

    # URL Ocorrencia
    path('ocorrencias_busca/', views.ocorrencias_index_busca, 
         name='ocorrencias_index_busca' ),
    path('ocorrencias_index/', views.ocorrencias_index, 
         name='ocorrencias_index' ),
    # CRUD Ocorrencia
    path('ocorrencias_id/create_ocorrencia/', views.ocorrenciaIndex , 
         name='ocorrenciaIndex' ),
    path('ocorrencias_id/<int:id_ocorrencia>/detail/', 
         views.ocorrencias_index_id, 
         name='ocorrencias_index_id' ),
    path('ocorrencias_id/<int:id_ocorrencia>/update/', 
         views.ocorrenciaUpdate, 
         name='ocorrenciaUpdate' ),
     # URL Eventos
    path('index_eventos/', views.eventos, name='eventos' ),
    path('eventos_busca/', views.eventos_busca, name='eventos_busca' ),
     # CRUD Eventos
    path('eventos_busca/<int:eventos_id>/detail/', views.eventos_id, 
         name='eventos_id' ),
    path('eventos_busca/create_eventos/', views.create_eventos, 
         name='create_eventos' ),
    path('eventos_busca/<int:eventos_id>/update_eventos/', 
         views.update_eventos, name='update_eventos' ),
    path('eventos_busca/<int:eventos_id>/delete/', views.delete, 
         name='delete' ),



     # User Register
    path('user/create_user/', views.register, name='register' ),
    path('user/login/', views.login_views, name='login_views' ),
    path('user/logaut/', views.logaut_views, name='logaut_views' ),
    path('user/update/', views.user_update, name='user_update' ),
















]


project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('porteiros/', include('contact.urls')),
    path('moradores/', include('moradores.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Apartamento(models.Model):
    numero_apartamento = models.CharField(max_length=50)
    anda = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.numero_apartamento

class Categoria(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nome

class Carro(models.Model):
    nome_proprietario = models.CharField(max_length=254)
    placa = models.CharField(max_length=10)
    cor = models.CharField(max_length=50, blank=True)
    modelo = models.CharField(max_length=50, blank=True)
    apartamento = models.ForeignKey(Apartamento, 
                                    on_delete=models.SET_NULL,
                                    blank=True, null=True
                                     )
    foto = models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')
    obs = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.nome_proprietario

class Moradore(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    nome = models.CharField(max_length=245)
    cpf = models.CharField(max_length=25)
    foto = models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')
    telefone = models.CharField(max_length=25)
    data_nascimento = models.CharField(max_length=12, blank=True)
    apartamento = models.ForeignKey(Apartamento, 
                                    on_delete=models.SET_NULL,
                                    blank=True, null=True
                                     )
    email = models.EmailField(max_length=254, blank=True)
    obs = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.nome

# Començando no index
class Registro_de_Visitante(models.Model):
    nome = models.CharField(max_length=245)
    cpf = models.CharField(max_length=25)
    telefone = models.CharField(max_length=25)
    data_registro = models.DateTimeField(default=timezone.now)
    foto = models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')
    obs = models.TextField(blank=True)
 
    def __str__(self) -> str:
        return self.nome

class Registros_de_Entrega(models.Model):
    tipos_de_entrega = models.CharField(max_length=254)
    codigo_de_rastreamento = models.CharField(max_length=100, null=False,
                                                blank=True)
    destino = models.CharField(max_length=254)
    apartamento = models.ForeignKey(Apartamento, 
                                    on_delete=models.SET_NULL,
                                    blank=True, null=True
                                     )
    data_registro = models.DateTimeField(default=timezone.now)
    obs = models.TextField(blank=True)
    foto_recebendo = models.ImageField(blank=True, 
                                       upload_to='pictures/%Y/%m/%d')
    foto_entrega = models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')
    horario_da_entrega = models.DateTimeField(null=True,blank=True)
    quem_recebeu = models.CharField(max_length=150, blank=True)

    def __str__(self) -> str:
        return self.tipos_de_entrega

class Visitante(models.Model):
    nome = models.CharField(max_length=254)
    # telefone = models.CharField(max_length=20, blank=True)
    apartamento = models.ForeignKey(Apartamento,
                                    on_delete=models.SET_NULL,
                                    blank=True, null=True
                                     )
    categoria = models.ForeignKey(Categoria, 
                                    on_delete=models.SET_NULL,
                                    blank=True, null=True
                                     )
    autorizador = models.ForeignKey(User, on_delete=models.SET_NULL,
                                    blank=True, null=True
                                     )
    
    data_entrada = models.DateTimeField(default=timezone.now)
    id_registro = models.CharField(max_length=50)
    obs = models.TextField(blank=True)
    saida = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:
        return self.nome

class Ocorrencia(models.Model):
    data = models.DateTimeField(default=timezone.now)
    nome_completo = models.CharField(max_length=254)
    
    ocorrencia = models.TextField()
    foto1 = models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')
    foto2 = models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL,
                                    blank=True, null=True)  # Campo owner que se relaciona ao usuário
    def __str__(self) -> str:
        return self.nome_completo

class Eventos(models.Model):
    local_evento = models.CharField(max_length=50)
    nome_responsavel = models.CharField(max_length=150)
    tipo_de_evento = models.CharField(max_length=100,  blank=True, null=True)
    apartamento = models.ForeignKey(Apartamento,
                                    on_delete=models.SET_NULL,
                                    blank=True, null=True
                                     )
    data_horas_evento = models.DateTimeField(default=timezone.now)
    horario_final_evento = models.CharField(max_length=25)
    nomes_autorizados = models.TextField()
    veiculos_autorizados = models.TextField()

contact/views/user_forms.py
from django.shortcuts import render, redirect
from contact.forms import RegisterForm, RegistrorUpadateForm
from django.contrib import messages, auth
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from functools import wraps


# Decorador para restringir acesso apenas a porteiros
def porteiro_required(view_func):
    @wraps(view_func)
    @login_required
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.groups.filter(name="porteiro").exists():  # Verifica se o usuário está no grupo 'porteiro'
            messages.error(request, 'Acesso negado! Apenas porteiros podem acessar esta área.')
            return redirect('contact:login_views')  # Redireciona para login se não for porteiro
        return view_func(request, *args, **kwargs)
    
    return _wrapped_view


@porteiro_required
def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario registrado com sucesso!')
            return redirect('contact:index')


    return render(
        request,
        'contact/user/register.html',
        {
            'form':form
        }
    )

@porteiro_required
def user_update(request):
    form = RegistrorUpadateForm(instance=request.user)

    if request.method != 'POST':
        return render(
        request,
        'contact/user/register.html',
            {
               'form':form
            }
        )
    
    form = RegistrorUpadateForm(data=request.POST , instance=request.user)

    if not form.is_valid():
        return render(
        request,
        'contact/user/register.html',
            {
               'form':form
            }
        )
    form.save()
    messages.success(request, 'Seu perfil foi atualizado com sucesso!')
    return redirect('contact:user_update')

def login_views(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)

            if user.groups.filter(name="porteiro").exists():  # Verifica se o usuário pertence ao grupo 'porteiro'
                messages.success(request, 'Bem-vindo ao sistema da portaria!')
                return redirect('contact:index')  # Redirecione para a página inicial da portaria

            messages.error(request, 'Acesso negado! Apenas porteiros podem acessar esta área.')
            auth.logout(request)
            return redirect('contact:login_views')  # Se não for porteiro, faz logout e redireciona

        messages.error(request, 'Login inválido')

    return render(
        request,
        'contact/user/login.html',
        {
            'form': form
        }
    )

@porteiro_required
def logaut_views(request):
    auth.logout(request)
    messages.info(request, 'Você saiu do Sistema!')
    return redirect('contact:login_views')

contact/templates/contact/eventos/create_eventos.html
{% extends "global/base.html" %}
{% block content %}
<div class="form-wrapper">
    <h1> Agendar eventos no Salão de Festa ou Deck </h1>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
    {% csrf_token %}
    <div class="form-content">
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {{ field.errors }}

                {% if field.help_text %}
                    <p class="help-text">{{ field.help_text }}</p>
                {% endif %}
            </div>        
        {% endfor %}
    </div>

    <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Cadastrar</button>
        </div>
    </div>
    </form>
</div>

<!-- Adicionando Flatpickr -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        flatpickr("#id_saida", {  // Certifique-se que o campo tem este ID
            enableTime: true,
            dateFormat: "Y-m-d H:i",  // Formato da data e hora
            time_24hr: true,  // Para horário em formato 24 horas
            locale: "pt", // Define o idioma como português
            onOpen: function (selectedDates, dateStr, instance) {
                // Ajusta o fuso horário para GMT-3 (Brasília) quando o campo for aberto
                const offset = -3 * 60; // Fuso horário de Brasília em minutos
                const currentDate = new Date();
                currentDate.setMinutes(currentDate.getMinutes() + currentDate.getTimezoneOffset() + offset);
                instance.setDate(currentDate);
            }
        });
    });
</script>

{% endblock content %}

contact/templates/contact/eventos/id_eventos.html
{% extends "global/base.html" %}

{% block content %}

    <div class="single-contact">
        <h1 class="single-contact-name">

            {{ id_eventos.local_evento }}
        </h1>
        <p><b>Local do Evento:</b> {{ id_eventos.local_evento }}</p>
        <p><b>Nome do Responsavel:</b> {{ id_eventos.nome_responsavel }} </p>
        <p><b>Tipo de Evento:</b> {{ id_eventos.tipo_de_evento }}</p>
        <p><b>Apartamento:</b> {{ id_eventos.apartamento }}</p>
        <p><b>Dia e Hora:</b> {{id_eventos.data_horas_evento }}</p>
        <p><b>Horario Final do Evento:</b> {{ id_eventos.horario_final_evento }}</p>
        <p><b>Nomes de Pessoas autorizados:</b> {{ id_eventos.nomes_autorizados }}</p>
        <p><b>Obs:</b> {{ id_eventos.veiculos_autorizados }}</p>

        <div class="contact-links">

            <a class="btn btn-link" 
                    href="{% url 'contact:update_eventos' id_eventos.id  %}">
                        Atualiza Agenda.
                </a>
            
            <form action="{% url 'contact:delete' id_eventos.id %}" method="post">

                {% csrf_token %}

                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes">
                    <button class="btn btn-link btn-delete " type="submit" > Confirma? </button>   
                {% else %}
                    <button class="btn btn-link btn-delete " type="submit" > Delete </button>    
                {% endif %}

            </form>
            
             <a class="btn btn-link btn-volta" 
                href="{% url 'contact:eventos' %}">Volta</a>
        </div>
    </div>

{% endblock content %}

contact/templates/contact/eventos/index_eventos.html
{% extends "global/base.html" %}
{% block content %}  
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption" >
                Agendamentos de Eventos Salão de Festa e Deck

                <div class="search">
                    <form action="{% url "contact:eventos_busca" %}" 
                    method="GET">
                        <input 
                        type="text" 
                        class="search-input"
                        placeholder="Busca"
                        id="search"
                        name="q"
                        value="{{ request.GET.q.strip }}"
                        >
                    </form>
                </div>
                
                <a href=" {% url "contact:create_eventos" %} " class="header-link">
                    <h2> Agendar eventos no Salão de Festa ou Deck </h2>
                </a>
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Nome</th>
                    <th class="table-header">Local do Evento</th>
                    <th class="table-header">APT</th>
                    <th class="table-header">Dia e Horario do Evento</th>
                    <th class="table-header">Final do Evento</th>
                </tr>
            </thead>
            
            <tbody>
                {% for agenda in page_obj %}
                  <tr class="table-row">

                    <td class="table-cel">
                        {{ agenda.id }}
                    </td>

                    <td class="table-cel">
                        <a href=" {% url "contact:eventos_id" agenda.id %} " 
                        class="table-link"
                        >
                        {{ agenda.nome_responsavel }}
                    </a>
                </td>
                
                <td class="table-cel">
                        {{ agenda.local_evento }}
                    </td>

                    <td class="table-cel">
                        
                        {{agenda.apartamento }}
                    </td>

                    <td class="table-cel">
                        {{ agenda.data_horas_evento }}
                    </td>

                    <td class="table-cel">
                        {{ agenda.horario_final_evento }}
                    </td>

                  </tr>
                {% endfor %}        
            </tbody>
        
        </table>
    </div>
{% endblock content %}